controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    
frontend_data:
    path: /api/data
    controller: App\Controller\ApiController::fetchData
    methods: [GET, POST, DELETE]
