controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    
frontend_data:
    path: /data
    controller: App\Controller\ApiController::fetchData
    methods: [GET, POST, DELETE]
ProductOfCategorie_data:
    path: /categories
    controller: App\Controller\ApiController::ProductOfCategorie
    methods: [GET]
Product_data:
    path: /produits
    controller: App\Controller\ApiController::ProductData
    methods: [GET]
image_product:
    path: /ip
    controller: App\Controller\ApiController::imageofProduct
    methods: [GET,POST]


search_produits:
    path: /search
    controller: App\Controller\ApiController::searchProduits
    methods: [POST,GET]


filtre_data:
    path: /filtre
    controller: App\Controller\ApiController::filtre
    methods: [GET,POST]

create_payment_intent:
    path: /create-payment-intent
    controller: App\Controller\ApiController::createPaymentIntent
    methods: [POST]

app_panier:
    path: /panier
    controller: App\Controller\ApiController::savePanier
    methods: [POST,GET]

app_commande:
    path: /commande
    controller: App\Controller\ApiController::commande


app_contact:
    path: /contact
    controller: App\Controller\ApiController::messages
    methods: ['POST']
app_the_message:
    path: /theMessage/{id}
    controller: App\Controller\HomeController::show