controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    
frontend_data:
    path: /api/data
    controller: App\Controller\ApiController::fetchData
    methods: [GET, POST, DELETE]
ProductOfCategorie_data:
    path: /api/categories
    controller: App\Controller\ApiController::ProductOfCategorie
    methods: [GET]
Product_data:
    path: /api/produits
    controller: App\Controller\ApiController::ProductData
    methods: [GET]
image_product:
    path: /api/ip
    controller: App\Controller\ApiController::imageofProduct
    methods: [GET,POST]


search_produits:
    path: /api/search
    controller: App\Controller\ApiController::searchProduits
    methods: [POST,GET]


filtre_data:
    path: /api/filtre
    controller: App\Controller\ApiController::filtre
    methods: [GET,POST]

create_payment_intent:
    path: /api/create-payment-intent
    controller: App\Controller\ApiController::createPaymentIntent
    methods: [POST]

attach_payment_method:
    path: /api/attach-payment-method
    controller: App\Controller\ApiController::attachPaymentMethod
    methods: [POST]

app_panier:
    path: /api/panier
    controller: App\Controller\ApiController::savePanier
    methods: [POST,GET]

app_commande:
    path: /api/commande
    controller: App\Controller\ApiController::commande

app_contact:
    path: /api/contact
    controller: App\Controller\ApiController::messages
    methods: ['POST']

app_the_message:
    path: /theMessage/{id}
    controller: App\Controller\HomeController::show

app_forgotPassword:
    path: /api/forgotPassword
    controller: App\Controller\ApiController::forgotPassword
    methods: ['POST']

app_userAdresses:
    path: /api/userAdresses
    controller: App\Controller\ApiController::userAdresses
    methods: ['POST']