controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: [POST]
    
frontend_data:
    path: /data
    controller: App\Controller\ApiController::fetchData
    methods: [GET, POST, DELETE]
ProductOfCategorie_data:
    path: /categories
    controller: App\Controller\ApiController::ProductOfCategorie
    methods: [GET]
Product_data:
    path: /produits
    controller: App\Controller\ApiController::ProductData
    methods: [GET]
image_product:
    path: /ip
    controller: App\Controller\ApiController::imageofProduct
    methods: [GET,POST]
